# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder "/Users/rory/cache", "/nfs", type: :nfs
  config.bindfs.bind_folder "/nfs", "/v-data"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 4000
    vb.cpus = 1
  end
end
