# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box"
  config.ssh.forward_agent = true

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder "/Volumes/Clotho/Users/rory/cache", "/nfs", type: :nfs
  config.bindfs.bind_folder "/nfs", "/v-data"

  config.vm.synced_folder "/Volumes/Clotho/bcbio-nextgen", "/bcbio-nextgen",
       id: "project", owned: "rory", group: "staff", mount_options: ["dmode=755,fmode=664"]
  config.vm.provider :virtualbox do |vb|
    vb.memory = 4000
    vb.cpus = 1
  end
end
